apiVersion: v1
kind: Namespace
metadata:
  name: tito-app

---
apiVersion: v1
kind: Service
metadata:
  name: titofe-service
  namespace: tito-app
  labels:
    app: tito
    tier: frontend
    stage: prod
spec:
  ports:
  - name: http
    port: 80               
  selector:                
    type: tito-fe
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.72.30.31