kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-vmc-wl-ds
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  datastoreurl: "ds:///vmfs/volumes/vsan:894b1c664fdb4292-b9a859b2b9c1d5df/" #Optional Parameter
  storagepolicyname: "vSAN Default Storage Policy"  #Optional Parameter
